In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv(r"F:\Buat Portofolio\E-Commerce Website\Data\Raw\List of Orders.csv")
order_details = pd.read_csv(r"F:\Buat Portofolio\E-Commerce Website\Data\Raw\Order Details.csv")
sales_target = pd.read_csv(r"F:\Buat Portofolio\E-Commerce Website\Data\Raw\Sales target.csv")

In [3]:
print("Orders:", orders.shape)
print("Order Details:", order_details.shape)
print("Sales Target:", sales_target.shape)

Orders: (560, 5)
Order Details: (1500, 6)
Sales Target: (36, 3)

In [4]:
orders.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [5]:
order_details.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [6]:
sales_target.head()

  Month of Order Date   Category   Target
0              Apr-18  Furniture  10400.0
1              May-18  Furniture  10500.0
2              Jun-18  Furniture  10600.0
3              Jul-18  Furniture  10800.0
4              Aug-18  Furniture  10900.0

**Orders**

In [7]:
orders.shape

(560, 5)

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    object
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: object(5)
memory usage: 22.0+ KB

In [9]:
orders.isnull().sum()

Order ID        60
Order Date      60
CustomerName    60
State           60
City            60
dtype: int64

In [10]:
orders.duplicated().sum()

np.int64(59)

In [11]:
orders["Order ID"].nunique()

500

In [12]:
orders["CustomerName"].nunique()

332

**Order Details**

In [13]:
order_details.shape

(1500, 6)

In [14]:
order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   float64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 70.4+ KB

In [15]:
order_details.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64

In [16]:
order_details.duplicated().sum()

np.int64(0)

In [17]:
order_details["Order ID"].nunique()

500

In [18]:
order_details["Category"].value_counts()

Category
Clothing       949
Electronics    308
Furniture      243
Name: count, dtype: int64

In [19]:
order_details["Sub-Category"].nunique()

17

**Sales**

In [20]:
sales_target.shape

(36, 3)

In [21]:
sales_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  36 non-null     object
 1   Category             36 non-null     object
 2   Target               36 non-null     float64
dtypes: float64(1), object(2)
memory usage: 992.0+ bytes

In [22]:
sales_target.isnull().sum()

Month of Order Date    0
Category               0
Target                 0
dtype: int64

In [23]:
sales_target.duplicated().sum()

np.int64(0)

In [24]:
sales_target["Category"].value_counts()

Category
Furniture      12
Clothing       12
Electronics    12
Name: count, dtype: int64

In [25]:
sales_target["Target"].describe()

count       36.000000
mean     12108.333333
std       2667.837541
min       9000.000000
25%      10050.000000
50%      11450.000000
75%      14500.000000
max      16000.000000
Name: Target, dtype: float64

In [26]:
sales_target["Category"].unique()

array(['Furniture', 'Clothing', 'Electronics'], dtype=object)

## Data Transformation

In [27]:
orders["Order Date"] = pd.to_datetime(
    orders["Order Date"],
    format="%d-%m-%Y"
)

orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    datetime64[ns]
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 22.0+ KB

In [28]:
sales_target["Month of Order Date"] = pd.to_datetime(
    sales_target["Month of Order Date"],
    format="%b-%y"
)

sales_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  36 non-null     datetime64[ns]
 1   Category             36 non-null     object
 2   Target               36 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 992.0+ bytes

In [29]:
missing_orders = set(order_details["Order ID"]) - set(orders["Order ID"])

len(missing_orders)

0

In [30]:
missing_details = set(orders["Order ID"]) - set(order_details["Order ID"])

len(missing_details)

1

## Merge Orders and Order Details

In [31]:
sales = orders.merge(
    order_details,
    on="Order ID",
    how="inner"
)

sales.shape

(1500, 10)

In [32]:
sales.head()

,Order ID,Order Date,CustomerName,State,City,Amount,Profit,Quantity,Category,Sub-Category
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,1275.0,-1148.0,7,Furniture,Bookcases
1,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,66.0,-12.0,5,Clothing,Stole
2,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,8.0,-2.0,3,Clothing,Hankerchief
3,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,80.0,-56.0,4,Electronics,Electronic Games
4,B-25602,2018-04-01,Pearl,Maharashtra,Pune,168.0,-111.0,2,Electronics,Phones

In [33]:
sales["Month"] = sales["Order Date"].dt.to_period("M")

In [34]:
sales_target["Month"] = (
    sales_target["Month of Order Date"]
    .dt.to_period("M")
)

sales[["Order Date", "Month"]].head()

  Order Date    Month
0 2018-04-01  2018-04
1 2018-04-01  2018-04
2 2018-04-01  2018-04
3 2018-04-01  2018-04
4 2018-04-01  2018-04

In [35]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Order Date    1500 non-null   datetime64[ns]
 2   CustomerName  1500 non-null   object
 3   State         1500 non-null   object
 4   City          1500 non-null   object
 5   Amount        1500 non-null   float64
 6   Profit        1500 non-null   float64
 7   Quantity      1500 non-null   int64
 8   Category      1500 non-null   object
 9   Sub-Category  1500 non-null   object
 10  Month         1500 non-null   period[M]
dtypes: datetime64[ns](1), float64(2), int64(1), object(6), period[M](1)
memory usage: 129.0+ KB

In [36]:
sales.isnull().sum()

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
Month           0
dtype: int64

In [37]:
sales.duplicated().sum()

np.int64(0)

In [38]:
sales.head()

,Order ID,Order Date,CustomerName,State,City,Amount,Profit,Quantity,Category,Sub-Category,Month
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,1275.0,-1148.0,7,Furniture,Bookcases,2018-04
1,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,66.0,-12.0,5,Clothing,Stole,2018-04
2,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,8.0,-2.0,3,Clothing,Hankerchief,2018-04
3,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,80.0,-56.0,4,Electronics,Electronic Games,2018-04
4,B-25602,2018-04-01,Pearl,Maharashtra,Pune,168.0,-111.0,2,Electronics,Phones,2018-04

In [39]:
sales = orders.merge(
    order_details,
    on="Order ID",
    how="inner"
)

In [40]:
sales[["Category"]].drop_duplicates()

sales["Category"].unique()

array(['Furniture', 'Clothing', 'Electronics'], dtype=object)

## Month Category

In [47]:
sales["Month"].min(), sales["Month"].max()

KeyError: 'Month'

In [ ]:
sales_target["Month"].min(), sales_target["Month"].max()

(Period('2018-04', 'M'), Period('2019-03', 'M'))

In [ ]:
sales["Category"].unique()

array(['Furniture', 'Clothing', 'Electronics'], dtype=object)

In [42]:
sales_target["Category"].unique()

array(['Furniture', 'Clothing', 'Electronics'], dtype=object)

In [45]:
monthly_sales = (
    sales
    .groupby(["Month", "Category"])
    .agg(
        Total_Sales=("Amount", "sum"),
        Total_Profit=("Profit", "sum"),
        Total_Quantity=("Quantity", "sum")
    )
    .reset_index()
)

monthly_sales.head()

KeyError: 'Month'

In [44]:
monthly_sales = monthly_sales.merge(
    sales_target[["Month", "Category", "Target"]],
    on=["Month", "Category"],
    how="left"
)

monthly_sales.head()

NameError: name 'monthly_sales' is not defined

In [51]:
monthly_sales["Target"].isnull().sum()

np.int64(0)

In [53]:
monthly_sales["Achievement %"] = (
    monthly_sales["Total_Sales"] /
    monthly_sales["Target"]
) * 100

monthly_sales.head()

,Month,Category,Total_Sales,Total_Profit,Total_Quantity,Target,Achievement %
0,2018-04,Clothing,13478.0,-184.0,251,12000.0,112.316667
1,2018-04,Electronics,11127.0,-351.0,75,9000.0,123.633333
2,2018-04,Furniture,8121.0,-3425.0,63,10400.0,78.086538
3,2018-05,Clothing,9518.0,-267.0,233,12000.0,79.316667
4,2018-05,Electronics,12807.0,-2523.0,116,9000.0,142.300000

## Data Warehouse

In [33]:
dim_customer = (
    sales[["CustomerName"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_customer["customer_id"] = (
    dim_customer.index + 1
)

dim_customer = dim_customer[
    ["customer_id", "CustomerName"]
]

dim_customer.head()

   customer_id CustomerName
0            1       Bharat
1            2        Pearl
2            3        Jahan
3            4       Divsha
4            5      Kasheen

In [34]:
dim_product = (
    sales[["Category", "Sub-Category"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_product["product_id"] = (
    dim_product.index + 1
)

dim_product = dim_product[
    ["product_id", "Category", "Sub-Category"]
]

dim_product.head()

   product_id     Category      Sub-Category
0           1    Furniture         Bookcases
1           2     Clothing             Stole
2           3     Clothing       Hankerchief
3           4  Electronics  Electronic Games
4           5  Electronics            Phones

In [35]:
dim_product[["product_id", "Category"]].drop_duplicates()

    product_id     Category
0            1    Furniture
1            2     Clothing
2            3     Clothing
3            4  Electronics
4            5  Electronics
5            6     Clothing
6            7     Clothing
7            8    Furniture
8            9     Clothing
9           10     Clothing
10          11     Clothing
11          12     Clothing
12          13    Furniture
13          14  Electronics
14          15  Electronics
15          16    Furniture
16          17     Clothing

In [36]:
dim_category = (
    sales[["Category"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_category["category_id"] = dim_category.index + 1

dim_category

      Category  category_id
0    Furniture            1
1     Clothing            2
2  Electronics            3

In [44]:
dim_location = (
    sales[["State", "City"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_location["location_id"] = (
    dim_location.index + 1
)

dim_location = dim_location[
    ["location_id", "State", "City"]
]

dim_location.head()

   location_id           State       City
0            1         Gujarat  Ahmedabad
1            2     Maharashtra       Pune
2            3  Madhya Pradesh     Bhopal
3            4       Rajasthan     Jaipur
4            5     West Bengal    Kolkata

In [45]:
dim_date = (
    sales[["Order Date"]]
    .drop_duplicates()
    .sort_values("Order Date")
    .reset_index(drop=True)
)

dim_date["date_id"] = (
    dim_date["Order Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

dim_date["day"] = dim_date["Order Date"].dt.day

dim_date["month"] = dim_date["Order Date"].dt.month

dim_date["month_name"] = dim_date["Order Date"].dt.strftime("%B")

dim_date["quarter"] = (
    "Q" + dim_date["Order Date"].dt.quarter.astype(str)
)

dim_date["year"] = dim_date["Order Date"].dt.year

AttributeError: Can only use .dt accessor with datetimelike values

In [46]:
dim_date = dim_date[
    [
        "date_id",
        "Order Date",
        "day",
        "month",
        "month_name",
        "quarter",
        "year"
    ]
]

KeyError: "['date_id', 'day', 'month', 'month_name', 'quarter', 'year'] not in index"

In [60]:
dim_date.head()

    date_id Order Date  day  month month_name quarter  year
0  20180401 2018-04-01    1      4      April      Q2  2018
1  20180403 2018-04-03    3      4      April      Q2  2018
2  20180405 2018-04-05    5      4      April      Q2  2018
3  20180406 2018-04-06    6      4      April      Q2  2018
4  20180408 2018-04-08    8      4      April      Q2  2018

In [ ]:
fact_sales = sales.merge(
    dim_customer,
    on="CustomerName",
    how="left"
)

fact_sales = fact_sales.merge(
    dim_product,
    on=["Category", "Sub-Category"],
    how="left"
)

fact_sales = fact_sales.merge(
    dim_location,
    on=["State", "City"],
    how="left"
)

fact_sales["date_id"] = (
    fact_sales["Order Date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

NameError: name 'dim_location' is not defined

In [62]:
fact_sales = fact_sales[
    [
        "Order ID",
        "date_id",
        "customer_id",
        "product_id",
        "location_id",
        "Quantity",
        "Amount",
        "Profit"
    ]
]

In [63]:
fact_sales = fact_sales.rename(
    columns={
        "Order ID": "order_id",
        "Quantity": "quantity",
        "Amount": "sales_amount",
        "Profit": "profit"
    }
)

In [64]:
fact_sales.head()

,order_id,date_id,customer_id,product_id,location_id,quantity,sales_amount,profit
0,B-25601,20180401,1,1,1,7,1275.0,-1148.0
1,B-25601,20180401,1,2,1,5,66.0,-12.0
2,B-25601,20180401,1,3,1,3,8.0,-2.0
3,B-25601,20180401,1,4,1,4,80.0,-56.0
4,B-25602,20180401,2,5,2,2,168.0,-111.0

In [65]:
dim_category = (
    sales[["Category"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_category["category_id"] = (
    dim_category.index + 1
)

fact_sales_target = monthly_sales.merge(
    dim_category,
    on="Category",
    how="left"
)

In [66]:
fact_sales_target["target_date"] = (
    fact_sales_target["Month"]
    .dt.to_timestamp()
)

fact_sales_target["date_id"] = (
    fact_sales_target["target_date"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

In [67]:
fact_sales_target = fact_sales_target[
    [
        "date_id",
        "category_id",
        "Target"
    ]
]

fact_sales_target = fact_sales_target.rename(
    columns={
        "Target": "target_amount"
    }
)

In [68]:
print("dim_customer:", dim_customer.shape)
print("dim_product:", dim_product.shape)
print("dim_location:", dim_location.shape)
print("dim_date:", dim_date.shape)

dim_customer: (332, 2)
dim_product: (17, 3)
dim_location: (26, 3)
dim_date: (307, 7)

In [69]:
print("fact_sales:", fact_sales.shape)
print("fact_sales_target:", fact_sales_target.shape)

fact_sales: (1500, 8)
fact_sales_target: (36, 3)

In [70]:
fact_sales.isnull().sum()

order_id        0
date_id         0
customer_id     0
product_id      0
location_id     0
quantity        0
sales_amount    0
profit          0
dtype: int64

In [37]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\ferran\miniconda3\envs\gpu-env\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\ferran\miniconda3\envs\gpu-env\lib\site-packages (2.9.13)
Requirement already satisfied: greenlet>=1 in c:\users\ferran\miniconda3\envs\gpu-env\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ferran\miniconda3\envs\gpu-env\lib\site-packages (from sqlalchemy) (4.15.0)

In [38]:
from sqlalchemy import create_engine

In [39]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/sales_dw"
)

In [40]:
with engine.connect() as connection:
    print("Database connected successfully!")

Database connected successfully!

In [75]:
dim_customer.to_sql(
    "dim_customer",
    engine,
    if_exists="replace",
    index=False
)

332

In [41]:
dim_category.to_sql(
    "dim_category",
    engine,
    if_exists="replace",
    index=False
)

3

In [76]:
dim_product.to_sql("dim_product", engine, if_exists="replace", index=False)

dim_location.to_sql("dim_location", engine, if_exists="replace", index=False)

dim_date.to_sql("dim_date", engine, if_exists="replace", index=False)

fact_sales.to_sql("fact_sales", engine, if_exists="replace", index=False)

fact_sales_target.to_sql(
    "fact_sales_target",
    engine,
    if_exists="replace",
    index=False
)

36

In [77]:
dim_customer.to_sql(
    "dim_customer",
    engine,
    if_exists="replace",
    index=False
)

dim_product.to_sql(
    "dim_product",
    engine,
    if_exists="replace",
    index=False
)

dim_location.to_sql(
    "dim_location",
    engine,
    if_exists="replace",
    index=False
)

dim_date.to_sql(
    "dim_date",
    engine,
    if_exists="replace",
    index=False
)

fact_sales.to_sql(
    "fact_sales",
    engine,
    if_exists="replace",
    index=False
)

fact_sales_target.to_sql(
    "fact_sales_target",
    engine,
    if_exists="replace",
    index=False
)

print("All tables successfully loaded!")

All tables successfully loaded!